info:
  app:
    name: sbas
    description: Spring Boot Admin Service
    version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /sbas

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#  server:
#    servlet:
#      context-path: /sbas

spring:
  application:
    name: Spring Boot Admin Service
  boot:
    admin:
      client:
        url: http://localhost:${server.port}/sbas
        instance:
          service-base-url: http://localhost:${server.port}
  profiles:
    active: secure



